name: fsrs
description: fsrs_rs_dart binding
version: 0.0.1
homepage: https://github.com/open-spaced-repetition/fsrs-rs-dart
repository: https://github.com/open-spaced-repetition/fsrs-rs-dart
issue_tracker: https://github.com/open-spaced-repetition/fsrs-rs-dart/issues
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  lints: ^2.0.1
  flutter_rust_bridge: 2.8.0
  freezed_annotation: ^2.2.0
  collection: ^1.18.0
dev_dependencies:
  test: ^1.21.4
  freezed: ^2.1.0+1
  build_runner: ^2.4.4
  ffigen: ^11.0.0
