cargo-features = ["edition2024"]

[package]
name = "fsrs_rs_dart"
version = "0.1.0"
edition = "2024"

[dependencies]
flutter_rust_bridge = "=2.10.0"
fsrs = { version = "2.0.4" }

[lib]
crate-type = ["staticlib", "cdylib"]
